### ISSUE TITLE
XSCAN, broken?

### ISSUE THREAD

**Issue by pkieltyka** [siddontang/ledisdb#121]
Hello,

Perhaps I am doing something wrong, but `xscan *` doesn't seem to return anything for me for a 2.7 gb database.

**Comment by pkieltyka** [comment]
hey @siddontang .. I think you should write some basic docs, and note the XSCAN comamnds. I finally just noticed HXSCAN .. which I think should be XHSCAN .. the "X" prefix noting the extensions / added commands to the redis protocol

**Comment by siddontang** [comment]
Sorry @pkieltyka, "X" makes you surprised, I will change it later. 

Btw, do you think it is necessary to do #117 or #120 ? 
I just notice that https://github.com/github/hub use "godep -r" feature, which makes the package management easy, but the import path looks very long and ugly :-)

**Comment by pkieltyka** [comment]
For 120, I agree using godep -r or this project: https://github.com/robfig/glock which is similar. I started using glock with my projects and really enjoy it.

For 117, I think redis api comparability is important.. But what do you mean specifically because I find ledis to already be very close to the same. I do think additional commands are fine and just prefix with an X.

**Comment by siddontang** [comment]
Thanks @pkieltyka 

I will use `godep -r` later, although the import path looks ugly :smile: 
For redis comparability, I mean maybe `del` can delete not KV data, but also Hash, List, etc... like in Redis, but it may cause some performance degradation and data upgrade. 

Btw, the `XSCAN` can be used correctly in your project?
