### ISSUE TITLE
multiple values RPUSH behaviour

### ISSUE THREAD

**Issue by iwanbk** [siddontang/ledisdb#127]
Hi,

I want to get clarification about  RPUSH behaviour when pushing multiple values
I use rocksdb, if that's matter.

Is it doing all or nothing push?

Let's say we have 100 elements to push. Is it possible that some elements are pushed but some elements are not?
I need it to handle the error (if happened). partial insert will complicate the problem.

I have checked t_list.go and there is t.Commit() there. So, looks like it will do a kind of transaction that will prevent partial insert.

**Comment by siddontang** [comment]
Hi @iwanbk , LedisDB uses RocksDB WriteBatch, which will guarantee atomic writing for multi values, so I think all elements will be pushed ok, except RocksDB has some  bugs in WriteBatch :smile:

**Comment by iwanbk** [comment]
thanks
