### ISSUE TITLE
Sort command

### ISSUE THREAD

**Issue by coleifer** [siddontang/ledisdb#129]
I was curious if Ledis implemented anything like Redis' `SORT` command ([docs here](http://redis.io/commands/sort)). The `sort` command is neat because you can sort using external keys:

> Sometimes you want to sort elements using external keys as weights to compare instead of comparing the actual elements in the list, set or sorted set. Let's say the list `mylist` contains the elements `1`, `2` and `3` representing unique IDs of objects stored in `object_1`, `object_2` and `object_3`. When these objects have associated weights stored in `weight_1`, `weight_2` and `weight_3`, `SORT` can be instructed to use these weights to sort `mylist` with the following statement:

```
SORT mylist BY weight_*
```

> The `BY` option takes a pattern (equal to `weight_*` in this example) that is used to generate the keys that are used for sorting. These key names are obtained substituting the first occurrence of `*` with the actual value of the element in the list (1, 2 and 3 in this example).

Even crazier is the fact that you can use hashes (via the ``->`` operator). An example might be you have a set of object IDs. These object IDs correspond to hashes, and you'd like to sort the object IDs based on a value in the corresponding hash:

> It is possible to use `BY` and `GET` options against hash fields with the following syntax:

```
SORT mylist BY weight_*->fieldname GET object_*->fieldname
```

> The string `->` is used to separate the key name from the hash field name. The key is substituted as documented above, and the hash stored at the resulting key is accessed to retrieve the specified hash field.

---------------------------------

This is a really neat feature and I was curious if there is anything similar in LedisDB, and if not, if that's something you plan to add?

Thanks for your work, this is an awesome project!

**Comment by siddontang** [comment]
Thanks @coleifer, `sort` looks complex, I will dive into it and evaluate the difficulty. But this function is so powerful that I also want to support it :smile: 

LedisDB can not check the type with a raw key, so maybe I will use `xhsort` for hash, `xlsort` for list, etc...

**Comment by coleifer** [comment]
Awesome thanks for the really quick reply. I can't think of a more complex Redis command, so I imagine you've got your work cut out for you! I'll keep an eye on this issue, and am glad to hear you're interested in trying to add something similar to LedisDB.

**Comment by siddontang** [comment]
hi @coleifer ,  I have supported `sort` command in develop branch, unlike redis, I use `xlsort` for list type, `xssort` for set type and `xzsort` for zset type

e.g.

```
ledis>mset w_1 1 w_2 2 w_3 3
OK
ledis>mset o_1 1 o_2 2 o_3 3
OK
ledis>lpush a 1 2 3
(integer) 3
ledis>xlsort a
1)  "1"
2)  "2"
3)  "3"
ledis>xlsort a desc
1)  "3"
2)  "2"
3)  "1"
ledis>xlsort a by w_*
1)  "1"
2)  "2"
3)  "3"
ledis>xlsort a by w_* get o_* get #
1)  "1"
2)  "1"
3)  "2"
4)  "2"
5)  "3"
6)  "3"
```

Redis's `sort` has some optimization for zset type,  but I don't have done it now, it is not a serious problem. 

I will add some docs and merge this into master branch later if possible. :-)

**Comment by coleifer** [comment]
:+1: :100:
