### ISSUE TITLE
Support *SCAN command for values

### ISSUE THREAD

**Issue by kouhate** [siddontang/ledisdb#137]
Hi, @siddontang ,

I can't find compatible commands for HSCAN, SSCAN and ZSCAN of redis.
I know XHSCAN, XSSCAN and XZSCAN already exist, but these iterate "key" not "value" or "field".
Perhaps those commands confuse who want to iterate values.

If you could support, I'd also like to ask you to support its reverse iteration ver.
Those should be useful in many case.

**Comment by osiloke** [comment]
+1

**Comment by kouhate** [comment]
Hi, @osiloke 

It's a good idea if you use ledisdb in a single node, but I'm planning to use xcodis.
Once you switch to cluster, all keys are distributed to multiple nodes.
So, this design will force us to query all nodes... (except for using hash tag {})

Hash type is grouped by key and sorted by field, and the data structure looks like column-oriented nosql.
If HSCAN is supported, we could use it like cassandra.

**Comment by siddontang** [comment]
Hi @kouhate , sorry for the later response. I have a long vacation for Chinese Spring Festive and will go to work next week. 

Supporting HSCAN may be easy, but like XSCAN compared to SCAN, the function may be different from HSCAN in Redis. So giving another name with X prefix may be a good choice, maybe you can help me name it :smile:

**Comment by kouhate** [comment]
Hi @siddontang, I'm glad to hear from you.

Now, ledis has a lot of redundant *SCAN commands such as HXSCAN, XHSCAN, HXREVSCAN, XHREVSCAN....
I suppose these are rarely used in production, because in app we should use key-name like table-name of relational database.
So, those only help our maintenance operation, I think.

IMHO, It is better to combine key iterable commands(HXSCAN, LXSCAN, ZXSCAN, SXSCAN...) to XSCAN, and provide options to select targeted data type. (simply changing the name HXSCAN to HKEYSCAN is not so bad)

Then, HXSCAN or XHSCAN should overwritten to support value or field iteration.
I recommend to use HXSCAN because most of all redis commands are prefixed by data type.

These may confuse ledis user, but will improve the compatibility with redis.

**Comment by siddontang** [comment]
Thanks @kouhate, using `HXSCAN` or other before is my fault, I may remove them later or reuse as your recommendation. :-)

I can not change `XSCAN` because of the compatibility.

**Comment by kouhate** [comment]
Thank you, @siddontang.

BTW, would you also support SXSCAN and ZXSCAN?
These are useful too.

**Comment by siddontang** [comment]
Sure. I think we could use another new name, not "scan", maybe "travel"?

**Comment by kouhate** [comment]
Hi @siddontang, maybe "range" or "slice" is more suitable.
"seek" is also proposable and the shortest.

**Comment by siddontang** [comment]
Hi @kouhate,  move to #138.
