### ISSUE TITLE
remove begin, commit and rollback

### ISSUE THREAD

**Issue by siddontang** [siddontang/ledisdb#140]
So far, we don't use these commands in any scenarios, and I don't hear any other programmers use these in production too. 

Instead, supporting these imports many complicated and unmaintained codes.

**Comment by jgoodall** [comment]
I would actually like to use this (with boltdb), but I dont see any documentation as to how. Trying to use ledis sorted sets with boltdb backend (for transactions) - is that even possible?

**Comment by siddontang** [comment]
Hi @jgoodall, using transaction with boltdb or lmdb is easy likes MySQL transaction using, below:

```
ledis> begin
ledis> set a 1
ledis> set b 2
ledis> commit
```

But is it necessary to support transaction in LedisDB? I've always wondered. 

+ Transaction is not universal, leveldb, rocksdb can not support it, and most of the ledisdb users use rocksdb as the backend. 
+ Transaction will block any other write operations, this may degrade performance. 
+ Above all, transaction leads to complexity. 

Btw, why should you use this feature?

**Comment by jgoodall** [comment]
Using ledis within a go application, want to use transactions with sorted sets, something like this (pseudo code):

    tx := db.Begin()
    a := tx.ZIncrBy(...)
    b := tx.ZRangeByScore(...)
    tx.Commit()

I need to increment a set and then get the scores, and am accessing the sorted sets from multiple goroutines

1. I dont see a way to do that in the [boltdb API](https://godoc.org/github.com/siddontang/ledisdb/store/boltdb#DB) (only see `put`, `get`, `delete`) - am I missing something obvious?
2. Is there a way to accomplish the above without using Locks?

Thanks. Ledis is a really nice package!

**Comment by siddontang** [comment]
Hi @jgoodall , in your scenario, `ZIncrBy` would increment the set and return the new score atomically, so you don't need a transaction, below may be ok:

```
db.ZIncrBy(...)
db.ZRangeByScore(...)
```

The boltdb API has a `Begin` method to start a transaction, but it is underlying, so I don't suggest to use it directly.

**Comment by siddontang** [comment]
I have Removed them.
