### ISSUE TITLE
optimize migrate db

### ISSUE THREAD

**Issue by siddontang** [siddontang/ledisdb#141]

**Comment by siddontang** [comment]
#138 @kouhate said blocking write operation would be a fatal problem.

But
1. migration is not often, or even would not be occurred if we pre plan enough nodes.
2. we can do resharding at some time, like middle night,  this would affect the whole system little. 

Btw, for codis, it would also block any write operation when migration.

**Comment by kouhate** [comment]
@siddontang, 

1. It is difficult to estimate enough nodes for the future at the time of startup.
Migration is always harmful even if it is rare. That is especially why I want to execute it more safely.

2. it's true, but this is not user friendly.
Furthermore, it would be true the larger the amount of keys grow, the longer blocking time take.

As you said before, setting a lock for the key that migration is in progress looks like the best way.

I guess scaling out with ease is one of the advantage to use it in production.

**Comment by siddontang** [comment]
@kouhate, maybe you are right.

This will be the optimization later, locking the key is not easy because I must check it in every write operations, this may be a huge work and cost time. 

I think another important thing for us is to verify the system (ledisdb + xcodis + redis-failover) can work well in production, and we can optimize the migration at the same time. 

I think porting people original redis data into this system is important too, I don't like codis's redis-port, so I decide to write a common one, [redis-canal](https://github.com/siddontang/redis-canal).

Btw, I think codis/xcodis is not easy to use, would you give some advices on improvement?

**Comment by siddontang** [comment]
Hi @kouhate , I just optimize migration, now it will not block other write problems, but only can be used safely with xcodis. I think it does not matter.

**Comment by kouhate** [comment]
Hi @siddontang, thank you for the improvement, and I want to make sure how it is non-blocking.

When migrating group-1 to group-2, as you know this is the case of using xcodis, the followings are expected:
1) Write-operation to the key which is not yet migrated is routed to group-1.
2) Write-operation to the key which is already migrated is routed to group-2.
3) Only the write-operation for the key migrating just now is blocked.

Are these implemented certainly?
According to my code reading, it seems the lock only prevent duplicated migration.
If those are not supported yet, even simple write-operation may easily bring inconsistency.

I suppose this issue should be discussed together with busy key routing one.

**Comment by siddontang** [comment]
Hi @kouhate, for xcodis, if a slot n is in migration, e.g, from group1 -> group2, xcodis will handle every key in n, first migrate the key to group2, then do the write operation in group2, whether the key is in group1 or already in group2. 

So I said the migration is only safe with xcodis now, because xcodis will guarantee the migration in group1, and write operation in group2.

**Comment by kouhate** [comment]
@siddontang, aha, it all makes sense now. Thanks for the clarification.

Btw, what will be the difference between redis-port and redis-canal?

**Comment by siddontang** [comment]
redis-port is powerful but a little complex, and can not support ledisdb well, so I decide to develop redis-canal, syncing redis data into redis/ledisdb.

I want redis-canal be a universal service, not only for xcodis. e.g, you can define your key routing rule and let redis-canal sync origin redis data into different places.

But I have not began to develop it, maybe this month. :-)

**Comment by kouhate** [comment]
That's nice.
I suppose this would be also useful for another project when not only porting but rehashing.
