### ISSUE TITLE
Cross compile application using ledis fails

### ISSUE THREAD

**Issue by jgoodall** [siddontang/ledisdb#143]
Any ideas how to workaround the following issue:

    $ GOOS=linux GOARCH=amd64 go build -o streams_$GOOS_$GOARCH
    Godeps/_workspace/src/github.com/siddontang/ledisdb/store/mdb/mdb.go:9:2: C source files not allowed when not using cgo: mdb.c midl.c

I am building my app on a Mac for Linux using go 1.4.2. My app depends on Ledis (v0.4-61-gb9d10ac). I am using the boltdb or memory backend, so I dont even need mdb support.

**Comment by siddontang** [comment]
Hi @jgoodall , it seems that go1.4 doesn't use cgo as default, you can see the news here https://golang.org/doc/go1.4, "Unless cgo is being used to build the package, the go command now refuses to compile C source files"

This may be a big problem for me, I use some c files too. I will see it tomorrow and think how to resolve it. 

Thank you.

**Comment by siddontang** [comment]
Hi @jgoodall, I think this is not the problem for ledisdb only, but also for any other projects using cgo too, for cross compile.

I try to rebuild a linux go version using `sudo CGO_ENABLED=1 GOOS=linux GOARCH=amd64 ./make.bash --no-clean` and then compile ledisdb, but it still fails with below error:

```
# runtime/cgo
ld: unknown option: --build-id=none
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I have no idea about how to fix it. LedisDB uses cgo in many places, not only in mdb. It may be a hard work to let it support cross compile. 

I think the only way now is to compile it in actual linux environment, not cross compile. :-)

Thank you.

**Comment by jgoodall** [comment]
Is using go 1.3 still working?

On Mar 10, 2015, at 10:06 PM, siddontang <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @jgoodall<https://github.com/jgoodall>, I think this is not the problem for ledisdb only, but also for any other projects using cgo too, for cross compile.

I try to rebuild a linux go version using sudo CGO_ENABLED=1 GOOS=linux GOARCH=amd64 ./make.bash --no-clean and then compile ledisdb, but it still fails with below error:

# runtime/cgo
ld: unknown option: --build-id=none
clang: error: linker command failed with exit code 1 (use -v to see invocation)


I have no idea about how to fix it. LedisDB uses cgo in many places, not only in mdb. It may be a hard work to let it support cross compile.

I think the only way now is to compile it in actual linux environment, not cross compile. :-)

Thank you.

�
Reply to this email directly or view it on GitHub<https://github.com/siddontang/ledisdb/issues/143#issuecomment-78187249>.


--
John Goodall  |  jgoodall@ornl.gov<mailto:jgoodall@ornl.gov>  |  (865) 446-0611
Team Lead, Situation Awareness and Visual Analytics team
Cyber & Information Security Research group
Oak Ridge National Laboratory

**Comment by siddontang** [comment]
go 1.3 seems not work too for cross compile.

I think a better way is to adding a build flag for ledisdb to disable cgo for cross compile, if you don't want to use cgo, you can not use leveldb, rocksdb and lmdb as the backend storage, can not use lua, and can not use ledis-cli. 

But I guess you may embed ledis into your own project as a package, so disabling above feature does not matter.

**Comment by jgoodall** [comment]
Yes, that is exactly what I want to do: embed ledis and use boltdb or in memory backends only. So is adding a build flag something you are going to move towards?

On Mar 11, 2015, at 8:57 AM, siddontang <notifications@github.com<mailto:notifications@github.com>> wrote:


go 1.3 seems not work too for cross compile.

I think a better way is to adding a build flag for ledisdb to disable cgo for cross compile, if you don't want to use cgo, you can not use leveldb, rocksdb and lmdb as the backend storage, can not use lua, and can not use ledis-cli.

But I guess you may embed ledis into your own project as a package, so disabling above feature does not matter.

�
Reply to this email directly or view it on GitHub<https://github.com/siddontang/ledisdb/issues/143#issuecomment-78257707>.


--
John Goodall  |  jgoodall@ornl.gov<mailto:jgoodall@ornl.gov>  |  (865) 446-0611
Team Lead, Situation Awareness and Visual Analytics team
Cyber & Information Security Research group
Oak Ridge National Laboratory

**Comment by siddontang** [comment]
Adding a tag may be not hard, only need work. But you may know that LedisDB will use cgo as default, so if you want to use it, you may pass a tag in your own build, like go build -tags 'nocgo'. 

I will try later and check whether it can be ok for cross compile.

**Comment by siddontang** [comment]
Hi @jgoodall, maybe you can use the latest master branch directly if you don't pass leveldb, rocksdb, lmdb, lua and linenoise into your build tags.

**Comment by jgoodall** [comment]
I found a way to build the linux binary on OS X using the [golang docker image](https://registry.hub.docker.com/_/golang/) and [boot2docker](http://boot2docker.io/).  Install `docker` (the client) and `boot2docker` (the linux vm) using [brew](http://brew.sh/):  `brew install docker boot2docker`. Then spin up a VM and use the 1.3 or 1.4.2 image to build the project that uses Ledis.

    boot2docker init
    boot2docker start
    $(boot2docker shellinit)
    docker run --rm -v `pwd`:/go/src/github.com/<username>/<project> -w /go/src/github.com/<username>/<project> golang:1.4.2 go build -o <binary>_linux_amd64

This will mount the current directory as a volume in the container into the proper gopath (`/go`), use the official golang image, and build a binary called `<binary>_linux_amd64`. Not ideal, but at least a workable solution.

This solves my issue, so not sure if you want to keep this open or not...

**Comment by siddontang** [comment]
Hi @jgoodall , golang docker image is linux based, so you can use it for your linux compile. I think this may be a better way for cross compile, e.g. if you want to build a windows version, you can use a windows docker too. 

Btw, do you build successfully using cross compile with latest ledisdb code?

**Comment by jgoodall** [comment]
I did not attempt to cross compile - only needed to build a linux binary on a Mac, and using the docker golang image that works fine.


On Mar 12, 2015, at 11:11 AM, siddontang <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @jgoodall<https://github.com/jgoodall> , golang docker image is linux based, so you can use it for your linux compile. I think this may be a better way for cross compile, e.g. if you want to build a windows version, you can use a windows docker too.

Btw, do you build successfully using cross compile with latest ledisdb code?

**Comment by siddontang** [comment]
:smile:
