### ISSUE TITLE
support large db index

### ISSUE THREAD

**Issue by siddontang** [siddontang/ledisdb#145]
Now ledisdb only supports 16 databases [0-15], although I try to supply a config to let it support 256, but lucky that this feature is not used.

Now the key format in the backend storage like this:

```
db index(1 byte) | data type(1 byte) | key lenth(2 byte) | key
```

The first byte is db index, if you want to support large db index, like 1024, 1 byte is not be enough. We can two bytes directly, because we must consider data backend compatibility, it a huge work to upgrade all data. 

Luckily, we can use a varint to handle db index, if db < 0x80, varint is the same as before, and  now the maximum db index is 15 (0x0F), so we don't need to change old data. 

@kouhate

**Comment by kouhate** [comment]
@siddontang, now you have changed db index to 16 as before.

Then, how many db index would you plan on supporting?

**Comment by siddontang** [comment]
use varint can support 2 ** 64 index, but it's too large, may be [0, 10240] or less

**Comment by kouhate** [comment]
That's enough to scale out, and it may be good to start from 1024 while an alternative plan to solve the performance issue of keeping huge routing table is not found.
Thanks:-)

**Comment by siddontang** [comment]
@kouhate, 1024 or 2048 may be enough, and I think zookeeper can save these with an acceptable performance. 

I hope I can support large index next week, then use it in xcodis. Next week another colleague will help me. So if you have any advice, please tell me.I hope we can improve the whole thing together.

**Comment by siddontang** [comment]
Hi @kouhate, I have supported large db index in develop, and later I will support in xcodis. 

Maybe you can help me test it. Thank you.

**Comment by kouhate** [comment]
Hi @siddontang, <code>make test_ledis</code> passed, and 10240 db also works well under replication environment.

Btw, xcodis seems to have a connection pool per db-index in order to reduce performance degradation, and its pooling capacity looks like 16.
Do you intend to increase the number to 1024 or more? This implementation may have some inefficiency for a large number of dbs.

**Comment by siddontang** [comment]
Thanks @kouhate 

I know the connection pool problem and will fix it later, may be tomorrow. 

> Do you intend to increase the number to 1024 or more? This implementation may have some inefficiency for a large number of dbs.

Above means the problem for zookeeper saving 1024 slots?

**Comment by kouhate** [comment]
Oh, I meant this is only for the connection problem, not for zookeeper.

**Comment by siddontang** [comment]
:smile: 

I think we can close this issue and move on.
