### ISSUE TITLE
你好，ledisdb能否在产品中使用？

### ISSUE THREAD

**Issue by Aegsea** [siddontang/ledisdb#148]
你好，请问下ledisdb目前是否稳定？能否用在生产环节中？有没有成功的案例？

**Comment by siddontang** [comment]
这个只能取决于你自己的判断。我们在生产环境中存储推送数据，session等，而且也有一些朋友告诉我他们也用于了生产环境，但这些可能对你来说没有任何帮助。

LedisDB现在仍旧是alpha版本(0.4 version release)，而且我现在几乎每天都在改进，如果你对这个很在意，建议你使用couchbase，redis或其它NoSQL。

谢谢。

**Comment by Aegsea** [comment]
好的，谢谢。我粗略看了下代码，ledisdb目前还没有主从同步的设计是吧？

**Comment by siddontang** [comment]
No, we have.
