### ISSUE TITLE
Add support for cockroachdb as database backend

### ISSUE THREAD

**Issue by pyros2097** [siddontang/ledisdb#151]

**Comment by siddontang** [comment]
Hi @pyros2097 , cockroachdb is a distributed kv store, and I think it's too huge as a backend storage.

**Comment by pyros2097** [comment]
I was thinking if we use cockroachdb, as at its core uses rocksdb you can directly connect its low level db functions to ledisdb and Maybe get the clustering, fault tolerance for ledisdb automatically

**Comment by siddontang** [comment]
This seems a good idea for ledisdb, but I have no time to see cockroachdb code.
Btw, we have used [xcodis](https://github.com/siddontang/xcodis) for cluster, [redis-failover](https://github.com/siddontang/redis-failover) for tolerance. 
But later, I want to build a cluster similar like elasticsearch or redis cluster architecture, maybe at that time, we can refer cockroachdb.
