### ISSUE TITLE
ZRange is terribly slow on high score

### ISSUE THREAD

**Issue by akhenakh** [siddontang/ledisdb#158]
This code is slower and slower as you increase the ZRange max value.
I've tried on different storage with the same results.
```
package main

import (
	"log"

	"github.com/siddontang/ledisdb/config"
	"github.com/siddontang/ledisdb/ledis"
)

func main() {
	// loading ledis config
	c, err := config.NewConfigWithFile("ledis.conf")
	if err != nil {
		log.Fatal(err)
	}
	// opening ledis
	lc, err := ledis.Open(c)
	if err != nil {
		log.Fatal(err)
	}
	defer lc.Close()

	// selecting database
	db, err := lc.Select(0)
	if err != nil {
		log.Fatal(err)
	}

	db.ZAdd([]byte("adxs"), ledis.ScorePair{1, []byte("toto")})

	_, err = db.ZRange([]byte("adxs"), 0, 999999999)
	if err != nil {
		log.Fatal(err)
	}
}
```

**Comment by siddontang** [comment]
Thanks @akhenakh , how about your data size in a size? only one?
Could you show me your benchmark test case?
zset uses an iterator which seeks to the first score 0 first, then one by one to the laster 99999999, if your size is big, this may be slow, especially for reverse range.

**Comment by akhenakh** [comment]
Run this code on your computer, empty db ! :)

**Comment by akhenakh** [comment]
No need for a bench this one ZRange takes 25.97s on a core i5

**Comment by siddontang** [comment]
Thanks @akhenakh , I find the problem, here is the code for zrange:

```
nv := 64
if count > 0 {
	nv = count
}

v := make([]ScorePair, 0, nv)
```
here count is 99999999, so make costs a very long time. Later I will use a default maximum count if possible.

**Comment by akhenakh** [comment]
Thank you!

**Comment by siddontang** [comment]
I have fixed it, you can update the code and try again. :-）

**Comment by akhenakh** [comment]
Awesome, thank you
