### ISSUE TITLE
LLEN performance ?

### ISSUE THREAD

**Issue by faaliyet** [siddontang/ledisdb#163]
assuming you already know, webapps often use lists like; comments, likes etc.. followers etc..
I see that; rocksdb rocks with ledisdb. however, never saw benchmark results for LLEN. does it full scan over list ? or it incr + 1 when we command lpush. I don;t think that fullscan is somehow faster than a local key - value. I short, I wonder LLEN performance and how it works :)

**Comment by siddontang** [comment]
In the backend storage, we will use a list meta size key, so LLEN is O(1) in LedisDB if the key in rocksdb cache, and O(lgN) if the key not in cache.

**Comment by faaliyet** [comment]
OK, then how this cache will work ? I think, my approach is something useful, that lpush lpop commands trigger incr +x/-x actions on metadata. 
```
we will use a list meta size key
```
"will use"? so, it's fullscan now?

**Comment by faaliyet** [comment]
however, after rethink about my approach, ltrim can be problematic :) may it better wih ``delete/flush - set```

**Comment by siddontang** [comment]
sorry, we use a meta key for list length and some other informations now. 

The cache in RocksDB is LRU, so if you use this list frequently (Every write operations for list will change meta key), the meta key may be in cache all the time.

**Comment by faaliyet** [comment]
LRU? well, so how about if we have a few millions list? pinterest uses millions of list data types with Redis, but it's not cost efficient for medium size web-apps. So, what performance we can expect from LedisDB using lists ?

**Comment by siddontang** [comment]
Sorry, I cannot give you the answer because I don't benchmark this scenario. 

The best case for using LedisDB is that you have lots of data exceeding memory but only a few is be used at some time. 

In my old product, a push server, I use list to store about 10,000,000 user messages (every user has maximum 20 messages), push messages to about 200,000 users at same time, it works well but I still think it has no reference.

**Comment by faaliyet** [comment]
I think, LedisDB is the only Redis list alternative out there. SSDB performance with lists is bad.
And lists are used often in webapps. So, maybe in the future, you can pay attention to this feature as LedisDB already has HA. Pinterest may also interest with this, http://blog.pivotal.io/pivotal/case-studies-2/using-redis-at-pinterest-for-billions-of-relationships to cut some $$. :)

**Comment by siddontang** [comment]
Yes, saving all data in redis costs much $$, this is not cost-effective. In my opinion, we can use cluster solution if one machine can not hold the data size and request rate.

Btw, I have been developing a distributed KV in our startup team, here https://github.com/reborndb, maybe you have some interests too.

**Comment by faaliyet** [comment]
I don;t know how it's different *internally* but benchmark results are very different from LedisDB, some operations perform much faster, some other perform slower. LPUSH / LRANGE example. I have a question. Why did you build this ? The reason is **distribution** ?

**Comment by faaliyet** [comment]
this one reminds me cockroachdb which is another newsql/nosql.

**Comment by siddontang** [comment]
This is my work, so I must build this :-) 

Don't care too much about the benchmark too, it has not be updated for a very long time.

**Comment by faaliyet** [comment]
How can you handle all this stuff ? Is it not your effort is too much ? :) you're playing with too many technologies.

**Comment by siddontang** [comment]
CockroachDB is only KV, but does not support other redis data structure and commands. 

Btw, our team has also been building a distributed SQL based on coackroachdb too. :-)

**Comment by siddontang** [comment]
I developed LedisDB in my spare time before I join my current team. And now I nearly has no time to improve it, badly!!!

**Comment by faaliyet** [comment]
Respect ! :) It seems like, you and your team gonna be famous in near future :) Tell me more about RebornDB, :) why and when we/developers should use rebornDB over LedisDB

**Comment by siddontang** [comment]
RebornDB is redis compatibility, but LedisDB is not. So LedisDB may be faster than RebornDB. 

LedisDB is my personal product, but RebornDB is a company product, I think it may be more robust. (Btw, I am still confident that LedisDB can be used in production too!!!)

Later, we will develop a really distributed system like Elasticsearch architecture which can re-shard data automatically and protect your data safely. 

In the end of this month, we will release a beta version which will be used in some company (our customer :-) ), then we will release a stable version in August or September. 

Of course, the distributed version may not be ready at that time. So you may still care the whole cluster and do something like re-sharding with command tool manually.

**Comment by faaliyet** [comment]
```Don't care too much about the benchmark too, it has not be updated for a very long time. ```
when we can see an updated benchmark of RebornDB :)

``1. install gorocks.a & levigo.a to GOPATH```
I think it's storage is powered by leveldb and rocksdb, right?

**Comment by siddontang** [comment]
Now we are developing code and don't know when to complete document, but I have add an issue here https://github.com/reborndb/qdb/issues/41, maybe next week.

Yes, RebornDB uses rocksdb, leveldb, goleveldb as the backend storage, but we will support more later.

**Comment by faaliyet** [comment]
Perfect ! how about it's license ? open source or some limited open source :)

**Comment by siddontang** [comment]
I think you can create an issue in qdb, not here.

**Comment by siddontang** [comment]
Now it is MIT, but I am not sure whether it will be changed later (I am not the co-founder:-) ).

But it will be open source forever.

**Comment by faaliyet** [comment]
```I think you can create an issue in qdb, not here.```
actually, our conversation turns to QA :) that's why I've changed the title, to make seo friendly. I'm really looking to see it in production. many promises & challenges in it :)

**Comment by siddontang** [comment]
Got it. :-)
