### ISSUE TITLE
纯Go版编译成功了  ledis-server运行好像没有提示输出 不知是不是成功了  而ledis-cli则提示"Please use linenoise to build again, or use redis-cli instead",请问怎么解决?

### ISSUE THREAD

**Issue by insionng** [siddontang/ledisdb#167]
实验了一下 redis-cli可以连接成功了,不知为何ledis-cli会出现这个错误,另外建议ledis-server启动的时候输出个欢迎信息,不然都不知是不是正常工作了.

**Comment by siddontang** [comment]
ledis-cli是不支持的，因为用的跟redis一样的cli，不支持windows，你可以考虑用一个windows编译好的redis cli来测试

可以参考
https://github.com/MSOpenTech/redis
https://github.com/ServiceStack/redis-windows/tree/master/src/msopentech/redis-64.2.8.17

**Comment by insionng** [comment]
好的 已经在用redis-cli了,准备在一个非常复杂的系统里用ledisdb,希望带给我好运~

**Comment by siddontang** [comment]
:-)
