### ISSUE TITLE
make through error cmd/ledis-load/main.go:6:2: cannot find package "github.com/siddontang/ledisdb/config" in any of:

### ISSUE THREAD

**Issue by darshan-ghumare** [siddontang/ledisdb#172]
#uname -a
Linux ubdesk1404 3.13.0-53-generic #89-Ubuntu SMP Wed May 20 10:34:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

#$PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/cloud/gocode/bin

#make
godep go install -tags 'linenoise ' ./...
cmd/ledis-load/main.go:6:2: cannot find package "github.com/siddontang/ledisdb/config" in any of:
        /usr/src/pkg/github.com/siddontang/ledisdb/config (from $GOROOT)
        /home/cloud/prototypes/ledisdb/src/github.com/siddontang/ledisdb/Godeps/_workspace/src/github.com/siddontang/ledisdb/config (from $GOPATH)
        /home/cloud/gocode/src/github.com/siddontang/ledisdb/config
cmd/ledis-load/main.go:7:2: cannot find package "github.com/siddontang/ledisdb/ledis" in any of:
        /usr/src/pkg/github.com/siddontang/ledisdb/ledis (from $GOROOT)
        /home/cloud/prototypes/ledisdb/src/github.com/siddontang/ledisdb/Godeps/_workspace/src/github.com/siddontang/ledisdb/ledis (from $GOPATH)

**Comment by darshan-ghumare** [comment]
$ make
godep go install -tags 'linenoise leveldb' ./...
Godeps/_workspace/src/github.com/BurntSushi/toml/encoding_types.go:10:2: cannot find package "encoding" in any of:
        /usr/src/pkg/encoding (from $GOROOT)
        /home/cloud/prototypes/ledisdb/src/github.com/siddontang/ledisdb/Godeps/_workspace/src/encoding (from $GOPATH)
        /home/cloud/gocode/src/encoding
        /home/cloud/gocode/bin/src/encoding
        /home/cloud/gocode/pkg/src/encoding
        /home/cloud/gocode/src/src/encoding
        /home/cloud/prototypes/ledisdb/src/encoding
godep: go exit status 1
make: *** [build] Error 1

**Comment by siddontang** [comment]
Hi @darshan-ghumare 

What's your GOPATH, GOROOT and  Go version?

**Comment by darshan-ghumare** [comment]
Thanks /siddontang.

$GOPATH
/home/cloud/gocode/:/home/cloud/gocode/bin:/home/cloud/gocode/pkg:/home/cloud/gocode/src:/home/cloud/prototypes/ledisdb

GOROOT not set

 go version
go version xgcc (Ubuntu 4.9.1-0ubuntu1) 4.9.1 linux/amd64

**Comment by siddontang** [comment]
Hi @darshan-ghumare , if you don't set GOROOT to your go installed path, you can not use the standard   package like encoding. 

ledisdb is not in the correct path, e,g, the source must be in ${GOPATH}/src/github.com/siddontang/ledisdb, you can see the readme for more build and install information. 

Thank you.

**Comment by darshan-ghumare** [comment]
cloud@ubdesk1404:~/prototypes/ledisdb/src/github.com/siddontang/ledisdb$ $GOPATH
-bash: /home/cloud/gocode/:/home/cloud/gocode/bin:/home/cloud/gocode/pkg:/home/cloud/prototypes/ledisdb/src/github.com/siddontang/ledisdb:/home/cloud/prototypes/ledisdb: No such file or directory
cloud@ubdesk1404:~/prototypes/ledisdb/src/github.com/siddontang/ledisdb$ make
godep go install -tags 'linenoise leveldb' ./...
Godeps/_workspace/src/github.com/BurntSushi/toml/encoding_types.go:10:2: cannot find package "encoding" in any of:
        /usr/lib/x86_64-linux-gnu/go/4.9/src/pkg/encoding (from $GOROOT)
        /home/cloud/prototypes/ledisdb/src/github.com/siddontang/ledisdb/Godeps/_workspace/src/encoding (from $GOPATH)
        /home/cloud/gocode/src/encoding
        /home/cloud/gocode/bin/src/encoding
        /home/cloud/gocode/pkg/src/encoding
        /home/cloud/prototypes/ledisdb/src/github.com/siddontang/ledisdb/src/encoding
        /home/cloud/prototypes/ledisdb/src/encoding
godep: go exit status 1
make: *** [build] Error 1

**Comment by siddontang** [comment]
Hi @darshan-ghumare , if you install your go like /usr/local/go, do you do `export GOROOT=/usr/local/go `?

**Comment by darshan-ghumare** [comment]
Hi siddontang,

Thats what I did.

$ $GOROOT
/usr/lib/x86_64-linux-gnu/go/4.9/: Is a directory

cloud@ubdesk1404:~/prototypes/ledisdb/src/github.com/siddontang/ledisdb$ make
godep go install -tags 'linenoise leveldb' ./...
Godeps/_workspace/src/github.com/BurntSushi/toml/encoding_types.go:10:2: cannot find package "encoding" in any of:
        /usr/lib/x86_64-linux-gnu/go/4.9/src/pkg/encoding (from $GOROOT)
        /home/cloud/prototypes/ledisdb/src/github.com/siddontang/ledisdb/Godeps/_workspace/src/encoding (from $GOPATH)
        /home/cloud/gocode/src/encoding
        /home/cloud/gocode/bin/src/encoding
        /home/cloud/gocode/pkg/src/encoding
        /home/cloud/prototypes/ledisdb/src/github.com/siddontang/ledisdb/src/encoding
        /home/cloud/prototypes/ledisdb/src/encoding
godep: go exit status 1
make: *** [build] Error 1

**Comment by siddontang** [comment]
Hi @darshan-ghumare , `/usr/lib/x86_64-linux-gnu/go/4.9/` doesn't seem a valid go root path, how do you install go? if you enter this path, what's the output for `ls`? do you see any "src", "bin" or "pkg" directory in it?

you can see more here https://golang.org/doc/install 

btw, can you run any other go program?

**Comment by darshan-ghumare** [comment]
Thanks.

Now, not able to find ledis-server

$ ledis-server
No command 'ledis-server' found, did you mean:
 Command 'redis-server' from package 'redis-server' (universe)
ledis-server: command not found

**Comment by siddontang** [comment]
Hi @darshan-ghumare 

ledis-server is installed in your GOPATH/bin directory, look it here.

later I will change it to install in local bin directory.

**Comment by darshan-ghumare** [comment]
Thank you so much siddontang.

**Comment by siddontang** [comment]
:-)
