### ISSUE TITLE
siddontang/snappy and siddontang/leveldb packages

### ISSUE THREAD

**Issue by pkieltyka** [siddontang/ledisdb#177]
Are these still necessary? they are pretty out of date..

ie. would be nice to see this used: https://github.com/golang/snappy

and.. for leveldb.. I dunno, but I'm sure a lot has been done.

**Comment by pkieltyka** [comment]
I'm trying to update the Docker image to the latest but running into issues with the dependency drift. Can you update to use golang/snappy which was previously google/go-snappy.

**Comment by siddontang** [comment]
ok, I will fix it.

**Comment by pkieltyka** [comment]
thank you :)
