### ISSUE TITLE
key设置过期时间后ldb文件减小不明显

### ISSUE THREAD

**Issue by bittoy** [siddontang/ledisdb#180]
测试发现key设置过期时间，当超过过期时间后保存数据的ldb文件会大小会减小一小部分，但是不会减小为0，请问是什么原因

**Comment by siddontang** [comment]
leveldb/rocksdb这种的会有阀值，当超过之后才会进行compact处理。

**Comment by bittoy** [comment]
理论上我的理解是这样的，当我给key设置过期时间时，当超过过期时间此key会被删除，那么保存其信息的ldb文件中也会删除此条数据，不然的话ldb文件会一直增长下去

**Comment by siddontang** [comment]
不会，LSM模型是使用的文件追加方式，你的任何delete操作是append到文件末尾的，而不是直接去对应的位置删除。

只有过了相应的阀值，才会触发compact。

**Comment by bittoy** [comment]
好的，请问阀值是在什么地方去查看与设置的

**Comment by siddontang** [comment]
这个你具体看下leveldb或者rocksdb的文档吧，如果用的default的goleveldb，也可以看下，不过leveldb貌似是改不了的，rocksdb或者goleveldb能改，那配置也足够会让人郁闷死，太多了。

另外，个人感觉这么点硬盘损耗其实不必太care。

**Comment by bittoy** [comment]
知道了，非常感谢
