### ISSUE TITLE
Auth support?

### ISSUE THREAD

**Issue by ukd1** [siddontang/ledisdb#182]
Ledis doesn't seem to support authentication; is that planned or being worked on? Would you accept a pull request?

**Comment by siddontang** [comment]
Supporting it may be easy, but I have no time to develop it, sorry.
So it is very appreciated that you can send me a PR. :-)

**Comment by ukd1** [comment]
@siddontang I'm working on it now, I'll open a WIP PR - would love your comments on my implemenation

**Comment by siddontang** [comment]
Great :-)

**Comment by ukd1** [comment]
Yay! Thanks @siddontang
