### ISSUE TITLE
Is pipeline like redis supported?

### ISSUE THREAD

**Issue by FlamingTree** [siddontang/ledisdb#193]

**Comment by siddontang** [comment]
No, we don't support pipeline.

**Comment by FlamingTree** [comment]
why? I just need buffer multi commands and send all buffer once, and recv response repeatly. is there problem?

**Comment by siddontang** [comment]
As you see above, you need buffer multi commands which is done by client, not server.

**Comment by FlamingTree** [comment]
I understand. redis's so-call pipelined seem to be client behaviour too, right?

**Comment by siddontang** [comment]
yes. server doesn't care how client sends commands, and handle them one by one.

**Comment by FlamingTree** [comment]
thanks~
