### ISSUE TITLE
嵌入式的使用，只能使用goleveldb吗

### ISSUE THREAD

**Issue by leedstyh** [siddontang/ledisdb#195]
不能使用rocksdb？

**Comment by siddontang** [comment]
可以，直接在config里面配置。

**Comment by leedstyh** [comment]
我是直接把config文件夹里那个.toml文件cp过来，就改了下里面，设置成rocksdb，但是运行说rocksdb没有注册。

我没有在lediadb里执行make，我想嵌入式的使用不需要这步吧

**Comment by siddontang** [comment]
需要，make的时候会带上rocksdb这个build tag，不然不会编译rocksdb这个package
或者你手动go build -tags "rocksdb"，前提是rocksdb的安装路径要在linux标准路径里面，/usr/local/include以及/usr/local/lib，如果如果你是用homebrew这些安装的应该能直接找到

**Comment by leedstyh** [comment]
哦好的我再试试，还有，这个嵌入式使用，是不是我的程序go build后把二进制仍到服务器就行，服务器不需要安装任何东西了

**Comment by siddontang** [comment]
得装rocksdb，因为是动态库

**Comment by leedstyh** [comment]
我试了下，安装了rocksdb（按提供的那个链接，`make shared_lib`）

`/usr/local/include`和`/usr/local/lib`都有

然后用的`go build -tags "rocksdb" t.go`的方式build了，但是运行的时候出错，信息如下：

`error while loading shared libraries: librocksdb.so.4.2: cannot open shared object file: No such file or directory`

**Comment by siddontang** [comment]
这明显是系统没找到你这个动态库，新开一个会话再试试，或者强制设置一下LD_LIBRARY_PATH，另外，你确定librocksdb.so.4.2这个在/usr/local/lib下面？

**Comment by leedstyh** [comment]
是的，是在`/usr/local/lib`

http://lizh.me/files/rocksdb.png

**Comment by leedstyh** [comment]
现在，我在`.profile`里添加了`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib`（是这样添加吧，现搜索的）

正常运行了。

学到了不少新东西，不过感觉用起来不太方便呢

**Comment by siddontang** [comment]
动态库对于任何程序都不方便。

在linux下面你也可以尝试静态编译rocksdb，这样就没有动态库路径的问题，但我没试过，不保证能成功。
