### ISSUE TITLE
Implement LREM

### ISSUE THREAD

**Issue by captncraig** [siddontang/ledisdb#197]
I have a use case where in redis I am using [LREM](http://redis.io/commands/lrem) to remove all occurrences of a specified item from a list. Ledis does not support this. Any cahnce of getting it implemented?

**Comment by captncraig** [comment]
Nevermind. I was able to do what I need with `LMCLEAR`

**Comment by FanyuxiNIE** [comment]
I meet some problem like yours,do you mean how to slove?what is LMCLEAR?
