### ISSUE TITLE
为什么ledis的zrange命令在leveldb上比ssdb要慢？

### ISSUE THREAD

**Issue by guileen** [siddontang/ledisdb#198]
因为ledis对redis协议的完全兼容，我们希望在产品中使用ledis而不是ssdb。

观察ledis官方网站上的性能测试图，zrange在leveldb上的性能是rocksdb的一半，而在rocksdb上的性能接近ssdb。ssdb本身是基于leveldb的。

这一点让我感到很疑惑。ssdb和ledis在原理上应该都是利用leveldb的key排序特性来实现的，他们的IO次数应该是一样的。是否ledis在迭代过程中相比ssdb有一个额外的IO操作，导致ledis的IO次数恰好是ssdb的两倍？

**Comment by siddontang** [comment]
Ledis也不是redis完全兼容的，[qdb](https://github.com/reborn/qdb)是redis兼容的。

Ledis比ssdb慢，主要原因在于go比c++要慢，另外，只要不是指数倍数的差距我觉得都可以接受。

**Comment by guileen** [comment]
对于Ledis在ZRANGE这个操作上的慢，应该不可能是go比c++慢导致的。go比c＋＋慢的因素在所有命令中都是相同的，包括，SET、GET这些基本操作也应该能成倍的表现出来。显然，SET、GET命令并不比ssdb慢很多。但ZRANGE则比ssdb慢得太多，显得不太合理。

非常高兴看到 qdb 这个完全redis兼容的项目出来。不知道未来 qdb 与 ledis的计划是怎么样的呢？此外发现 qdb 属于reborndb这个组织的，而这个组织也有一个reborndb 简介是redis兼容的。想要知道，是否适合在项目中使用qdb。

**Comment by siddontang** [comment]
为什么这么慢如果你有兴趣，欢迎提PR fix，我现在没有时间去弄这个 :-) 

对于ledis或者qdb，我们现在没有任何计划，太忙了，sorry。

**Comment by guileen** [comment]
非常感谢。qdb的代码看起来很赞。
