### ISSUE TITLE
etcd backend?

### ISSUE THREAD

**Issue by mmindenhall** [siddontang/ledisdb#199]
Would it be feasible to support [etcd](https://github.com/coreos/etcd) as a ledis backend?  The use case I have in mind is a networked appliance that can be deployed as a standalone unit (in which case would use boltdb as backend), or in a cluster for redundancy (in which case would use etcd).

**Comment by siddontang** [comment]
@mmindenhall 
I don't use etcd before, so I can't tell you whether feasible or not, but I don't think we will have a good performance even it can be. :-)
