### ISSUE TITLE
snapshot是不是自动存的镜像？怎么开启？

### ISSUE THREAD

**Issue by insionng** [siddontang/ledisdb#201]

**Comment by siddontang** [comment]
不好意思，没明白？
snapshot只是底层kv的机制，外面除了sync的时候会用，其他地方不会用的。

**Comment by insionng** [comment]
我看到snapshot目录一直好像是空的，所以问问怎么用上？

**Comment by siddontang** [comment]
这个外面不会用的，只会在sync的时候用到。sync会将当前的snapshot存放到一个文件，然后在同步。

**Comment by insionng** [comment]
大概明白了 谢谢~
