### ISSUE TITLE
Small install process note

### ISSUE THREAD

**Issue by nikolay-turpitko** [siddontang/ledisdb#216]
There is a "sanity check" at the top of ledisdb/dev.sh:

    if [[ "$LEDISTOP" == "${LEDISTOP/\/src\/github.com\/siddontang\/ledisdb/}" ]]; then
        echo "WARNING: LEDISTOP($LEDISTOP) does not contain src/github.com/siddontang/ledisdb"
        exit 1
    fi

The issue is with that `exit` command.
Installation guide in the README suggested to `source` this file, so this `exit` leads to surprisingly closed shell session. You, probably, should use `return` instead.

Well, may be MacOS doesn't close window till you manually close it, but Ubuntu does.

It's a rather cosmetic issue, but may be a first frustrating impression for newcomers. 

I tried to replace `exit` with `return` on my local copy (Ubuntu 14.04.3 LTS, GNU bash, version 4.3.11(1)-release), it works as expected - exits script without closing bash session. Cannot check on MacOS or Windows though.

**Comment by siddontang** [comment]
Hi @nikolay-turpitko , in my mac, running `return` will return "return: can only `return' from a function or sourced script".  :-)

**Comment by nikolay-turpitko** [comment]
Well, don't know how to fix it then. May be just add something like `read -n1 -rsp $'Press any key to exit...\n'` before exit to let user read the message before window disappears?

**Comment by siddontang** [comment]
@nikolay-turpitko 
how about `false`? can you help me test in linux?

**Comment by nikolay-turpitko** [comment]
Well, I placed confirmation before exit like

    # LEDISTOP sanity check
    if [[ "$LEDISTOP" == "${LEDISTOP/\/src\/github.com\/siddontang\/ledisdb/}" ]]; then
        echo "WARNING: LEDISTOP($LEDISTOP) does not contain src/github.com/siddontang/ledisdb"
        read -n1 -rsp $'Press any key to exit...\n'
        exit 1
    fi

When project placed in the wrong dir it give me a chance to read message before exit and close terminal window. In the right place it works as usual. Sorry, if I misunderstand your question.

**Comment by siddontang** [comment]
@nikolay-turpitko 
what I mean is using `false` instead of `exit 1` like : 
```
if []; then
   echo 
   false
fi
```

This can work in my mac osx, how about in your linux system?

**Comment by nikolay-turpitko** [comment]
Yes, this works perfect in Ubuntu!

**Comment by siddontang** [comment]
Hi @nikolay-turpitko 
Can you send me a PR for this? :-)
