### ISSUE TITLE
Can't compile with Lua with Ubuntu 14.04.3

### ISSUE THREAD

**Issue by Aurlin** [siddontang/ledisdb#217]
Hi,

It's not really an issue (not sure ?), but some informations :)
We can't compile LedisDB with Lua 5.1 under **Ubuntu 14.04.3** because there is this error : 
```
godep go install -tags 'lua' ./...
# github.com/siddontang/ledisdb/vendor/lua
/usr/bin/ld: cannot find -llua
collect2: error: ld returned 1 exit status
godep: go exit status 2
make: *** [build] Error 1
```
Even if, in **dev.sh** the correct flag is set 
`CGO_LDFLAGS="$CGO_LDFLAGS -L$LUA_DIR/lib -llua5.1"`

Because, in the file **./vendor/lua/lua.go**, there is **one line** : 
```
`#cgo LDFLAGS: -llua
```
which override the flag ! (I think)

**Comment by siddontang** [comment]
Hi @Aurlin 

How do you install lua? does liblua.so not in the lua dir?

**Comment by Aurlin** [comment]
Hi,
Yes, everythings works, but i have to edit the file **./vendor/lua/lua.go** and change this line 
``#cgo LDFLAGS: -llua``
to
``#cgo LDFLAGS: -llua5.1``

**Comment by siddontang** [comment]
This is not a universal way for other users :-) 
Maybe this is a bug and we will try to fix it. 

How do you install your lua?

**Comment by Aurlin** [comment]
I use apt-get like this ``apt-get install lua5.1 lua5.1-dev``
