### ISSUE TITLE
Command names in the ledis.call() should not be case sensetive

### ISSUE THREAD

**Issue by nikolay-turpitko** [siddontang/ledisdb#218]
Eval itself seems to work:

redis ledisdb.socket> EVAL 'return ARGV[1]' 0 42
"42"

But cannot call anything on ledis object:

redis ledisdb.socket> EVAL "return ledis.call('ECHO', 'zzz')" 0
(error)  command not found

Or do I missing something?

**Comment by nikolay-turpitko** [comment]
It seems, that script eventually works:

redis ledisdb.socket> EVAL "ledis.call('set', 'answer', 42)" 0
(nil)
redis ledisdb.socket> get answer
"42"

But when I invoke script from app via redigo there is some issue. They have:
https://github.com/garyburd/redigo/blob/master/redis/script.go#L62

    func (s *Script) Do(c Conn, keysAndArgs ...interface{}) (interface{}, error) {
        v, err := c.Do("EVALSHA", s.args(s.hash, keysAndArgs)...)
        if e, ok := err.(Error); ok && strings.HasPrefix(string(e), "NOSCRIPT ") {
            v, err = c.Do("EVAL", s.args(s.src, keysAndArgs)...)
        }
        return v, err
    }

And you return: https://github.com/siddontang/ledisdb/blob/81381343f881670b41762e7eff0f4f4b7ac6eb9c/server/cmd_script.go#L80

    if evalSha1 {
        return fmt.Errorf("missing %s script", key)
    }

There is no "NOSCRIPT " in your error description, so their logic won't work. Not a big deal, I'll try to preload script, but if you wish, you may add this string to make it more convenient for redigo users.

**Comment by nikolay-turpitko** [comment]
And please add to doc that your global object is "ledis" not "redis" ;-)

**Comment by nikolay-turpitko** [comment]
I have to reopen this issue, cause I think I find what was wrong with the first example. This one works:

redis ledisdb.socket> eval "return ledis.call('echo', 'zzz')" 0
"zzz"

But this one - not:

redis ledisdb.socket> EVAL "return ledis.call('ECHO', 'zzz')" 0
(error) command not found

Redis work with both upper and lower case.

**Comment by nikolay-turpitko** [comment]
I think, these should be documented in the EVAL command description as a deviations from Redis (at least):

* global object name: redis -> ledis
* command names in the ledis.call() are case sensitive (lowercase accepted only)
* ledis.call('hmget', ...) returns empty strings instead of boolean for absent keys

**Comment by siddontang** [comment]
Hi @nikolay-turpitko 
Can you send a PR to help me fix it?

**Comment by nikolay-turpitko** [comment]
Checked with redis-cli, command names are no longer case sensitive.
Comments added to Lua script-related commands. Fixed.
