### ISSUE TITLE
修改了配置还是只支持16个配置

### ISSUE THREAD

**Issue by q1101151** [siddontang/ledisdb#229]
底层用的是 rocksdb   
Set the number of databases. You can use `select dbindex` to choose a db.
dbindex must be in [0, databases - 1].
Default databases is 16, maximum is 10240 now.
databases = 17
 这里不是说最多支持10240吗 为什么我怎么改都只支持16个

**Comment by q1101151** [comment]
问题解决了

**Comment by siddontang** [comment]
ok
