### ISSUE TITLE
Is there support to use pre-filled RocksDB as backend?

### ISSUE THREAD

**Issue by agnibha** [siddontang/ledisdb#238]
@siddontang If so, can such a backend be supported by xcodis?

**Comment by siddontang** [comment]
Hi @agnibha 
I don't test with pre-filled before. 

Sorry that I don't understand your scenario exactly? if you want to use origin ledisdb's data in xcodis, I think not ok, maybe you should do a dump + load.

**Comment by agnibha** [comment]
We have a LedisDB which we fill using a RocksDB snapshot. When we do a ledis-load on a ledisDB instance, we can get the data using the CLI.

When we use xcodis to be the proxy for this ledis instance, we can't fetch the keys using the proxy.
Is there a way we can restore the snapshot with xcodis proxy in place?

**Comment by siddontang** [comment]
We can't use xcodis with origin ledisdb data directly, because xcodis will hash key to different db with `index = hash(key) % 1024`.
So maybe you save a data in db 0 in ledisdb, but it will be passed to db n in xcodis.

**Comment by agnibha** [comment]
Okay. I get it. I have a read-only use-case, which can expand to read-write later.
So, if we reverse-engineer our code to write the data to `index = hash(key) % 1024`, can we then use xcodis to fetch data for us?

**Comment by siddontang** [comment]
maybe yes, but this may only work if you have one ledisdb.

**Comment by agnibha** [comment]
Also, is there a way of using a snapshot to fill data into a cluster of ledisdb's?

**Comment by siddontang** [comment]
Sorry, none. 
Codis has a tool redis-port which can do this, but now ledisdb doesn't support redis replication.

**Comment by agnibha** [comment]
Thanks @siddontang for all the help.
