### ISSUE TITLE
Remove item from list like LREM

### ISSUE THREAD

**Issue by jrudio** [siddontang/ledisdb#246]
Since it's not currently implemented, how can I mock something like LREM?

**Comment by siddontang** [comment]
I think LREM is hard to support in ledisdb, as you see, we save list like key:1 -> a, key:2 -> b, key:3 -> c, if we delete b, we will update all following items' key, so origin key:3 -> c may key:2 -> c.

**Comment by jrudio** [comment]
So the issue is that it's hard to update all the keys after `b`?

I attempted to do something like LREM, but could only remove 1 occurrence, anymore and my tests wouldn't pass. 

Here's my mockup [LRemOnce](https://gist.github.com/jrudio/66d51abbf8dfb78e22472e5bfc88ae27) and the [tests for it](https://gist.github.com/jrudio/456cac6226ff91ca5e291de1891d9c82)

**Comment by siddontang** [comment]
Seem no problem, but as you see, if the list is too huge, we may meet a very big performance problem.

**Comment by jrudio** [comment]
Very true!
