### ISSUE TITLE
Vendoring

### ISSUE THREAD

**Issue by pkieltyka** [siddontang/ledisdb#249]
Please target go1.6+ and use proper vendoring, the build process is very confusing and broken

**Comment by siddontang** [comment]
hi @pkieltyka 

Now we use vendor in cmd folder like etcd does

**Comment by pkieltyka** [comment]
@siddontang ah, you've put the files in cmd/vendor and link it.. how come you do this though? why not just keep it in ./vendor?

also, what version of RocksDB is ledisdb compatible with? I tried v4.8 but had compile errors

**Comment by siddontang** [comment]
Hi @pkieltyka 

The vendor use is from etcd, see https://github.com/coreos/etcd/tree/master/cmd
If we put vendor in ./vendor, other use ledisdb as library will import this vendor too. 

I will fix the compile errors later.

**Comment by siddontang** [comment]
Hi @pkieltyka 
What's the compile error? I use 4.11 but it's ok.

**Comment by pkieltyka** [comment]
@siddontang thanks for the reply, I tried v4.9+ and it works great.

also, perhaps update the Makefile for production builds to setup the link etc.. or add it to the notes. I'm going to update the Dockerfile/build now too

**Comment by siddontang** [comment]
@pkieltyka 

Dynamic linking is not convenient, maybe we can use https://github.com/cockroachdb/c-rocksdb instead.
