### ISSUE TITLE
Ledis和SSDB有没有共同问题？

### ISSUE THREAD

**Issue by wangxingge** [siddontang/ledisdb#250]
前段时间在使用SSDB做选型的时候，发现了SSDB的持续高速写的时候过几天就会发生无法继续写或者读的情况， 作者说这是LevelDB的问题。

Ledis用Rocks 也是LevelDB生的孩子，不知道有没有SSDB的病啊，会不会遗传呢。

**Comment by baotiao** [comment]
你可以试试 Pika 这个项目, 我们对底下rocksdb 做了挺多的调整.  https://github.com/Qihoo360/pika

**Comment by siddontang** [comment]
@baotiao 做广告不带这样的。。。

**Comment by wangxingge** [comment]
@baotiao 我去看一下。。。

**Comment by wangxingge** [comment]
用ledis还有一个原因是用go写的。。。。。

**Comment by siddontang** [comment]
任何SST架构的都有这个问题，但相比于leveldb，rocksdb有一堆参数可以调，能稍微缓和一下

**Comment by wangxingge** [comment]
谢谢啊。我在想想。

**Comment by baotiao** [comment]
@wangxingge   哈哈.. 你可以测试对比一下. 目前我们线上有几百个实例, 而且根据挺多内部, 外部用户的测试效果, 性能好很多的.
