### ISSUE TITLE
嵌入rocksdb出错

### ISSUE THREAD

**Issue by wangcn** [siddontang/ledisdb#274]
在dev.sh里设置了相应路径后，make时报错
could not determine kind of name for C.rocksdb_options_set_allow_os_buffer
could not determine kind of name for C.rocksdb_options_set_disable_data_sync

我的环境：
rocksdb代码是通过git拉取，版本是5.2.
ledis版本是380835a0ca70929fb26d78f57444efaaf44abcac
go版本是1.7.4
os是opensuse 42.2

**Comment by siddontang** [comment]
现在没支持这么新的 rocksdb，后面有时间我升级一下

**Comment by wangcn** [comment]
目前4.13可以用
