### ISSUE TITLE
store rocksdb is not registered

### ISSUE THREAD

**Issue by penuel-leo** [siddontang/ledisdb#276]
按照文档安装完ledis, make test前几个都OK；
然后安装完rocksDB和snappy，修改了dev.sh里的路径后；
使用make clean or make 会报

>Makefile:3: *** multiple target patterns.  Stop.

如果直接启动
``` ./bin/ledis-server -config=./etc/ledis.conf ```
会报

>store rocksdb is not registered

**Comment by siddontang** [comment]
go build 的时候带上了 -tags rocksdb 了吗？ 你 make 的时候输出输出是怎样的？

**Comment by penuel-leo** [comment]
我将ledisdb rm后，重新安装就行了；
但是报错和[issue274](https://github.com/siddontang/ledisdb/issues/274)一样，
请问现在rocksdb支持到哪个版本

**Comment by wangcn** [comment]
@penuel-leo 我目前用4.13编译通过的。

**Comment by siddontang** [comment]
4.13, 5.0+ 的一些 API 改了，没法兼容。这个我后面考虑用 https://github.com/tecbot/gorocksdb 的静态编译来解决下这个问题

**Comment by penuel-leo** [comment]
使用4.13编译过了，但是在执行RocksDB support里面的步骤
```make clean && make```出现错误
>GO15VENDOREXPERIMENT="1" go build -o bin/ledis-server -tags 'rocksdb' cmd/ledis-server/*
cmd/ledis-server/main.go:15:2: cannot find package "github.com/siddontang/ledisdb/config" in any of:
	/usr/local/go/src/github.com/siddontang/ledisdb/config (from $GOROOT)
	/home/allen/go/src/github.com/siddontang/ledisdb/config (from $GOPATH)
cmd/ledis-server/main.go:16:2: cannot find package "github.com/siddontang/ledisdb/server" in any of:
	/usr/local/go/src/github.com/siddontang/ledisdb/server (from $GOROOT)
	/home/allen/go/src/github.com/siddontang/ledisdb/server (from $GOPATH)
make: *** [build] Error 1

发现GOPATH找的位置不对，``` echo $GOPATH ```
>/home/allen/.go

自己看了下source dev.sh里面$GOPATH还是正确的，不知道在哪一步给换掉了?

**Comment by siddontang** [comment]
这个不清楚，你可以重新在设置一下  GOPATH 吧
