### ISSUE TITLE
etc/ledis.conf配置了rocksdb为什么还是找libleveldb.so

### ISSUE THREAD

**Issue by penuel-leo** [siddontang/ledisdb#279]
配置文件如下:
```xml
# Choose which backend storage to use, now support:
#
#   leveldb
#   rocksdb
#   goleveldb
#   memory
#   
db_name = "rocksdb"

# If not set, use data_dir/"db_name"_data
db_path = ""

# Sync commit to disk if possible
#  0: no sync 
#  1: sync every second 
#  2: sync every commit 
db_sync_commit = 0
```
执行命令：
```shell
bin/ledis-server -config=./etc/ledis.conf -db_name=rocksdb
```
结果报错如下:
***bin/ledis-server: error while loading shared libraries: libleveldb.so.1: cannot open shared object file: No such file or directory***

ps:我只装了rocksdb相关lib，没装leveldb的

**Comment by siddontang** [comment]
因为你可能之前加上了 -tag=leveldb 编译过

**Comment by penuel-leo** [comment]
找到问题了，因为dev.sh里面会根据leveldb配置的路径找leveldb，如果找到则会给$GO_BUILD_TAGS增加一个tag(leveldb)，所以执行的时候会取这个$GO_BUILD_TAGS变量；
我本地刚好有leveldb在配置的路径下。。。
将dev.sh 的leveldb路径修改为不存在的路径即可；
多谢提醒。
