### ISSUE TITLE
ledis-server会stop，同步报错

### ISSUE THREAD

**Issue by penuel-leo** [siddontang/ledisdb#283]
遇到两个奇怪问题：
### 1：使用nohup启动ledis-server，几个小时后，会自动停进程 ###
>ledis-server is closing
[2017/03/13 18:09:05] replication.go:397 [Info] remove slave 172.30.30.235:6380
ledis-server is closed

#### Slave节点 ####
>127.0.0.1:6380> role
1 )  "slave"
2 )  "172.30.30.231"
3 )  (integer) 6380
4 )  "connected"
5 )  (integer) 6

>127.0.0.1:6380> get a
(nil)

nohup文件报错：
>[2017/03/14 11:38:02] replication.go:56 [Error] decode batch log error leveldb: batch corrupted: bad record: invalid key length
[2017/03/14 11:38:02] replication.go:56 [Error] decode batch log error leveldb: batch corrupted: bad record: invalid key length
[2017/03/14 11:38:02] replication.go:56 [Error] decode batch log error leveldb: batch corrupted: bad record: invalid key length

#### Master节点 ####
>127.0.0.1:6380> role
1 )  "master"
2 )  (integer) 6
3 )  &nbsp;&nbsp;1)  1)  "172.30.30.235"
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2)  "6380"
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3)  "6"

>127.0.0.1:6380> get a
"b"

**Comment by siddontang** [comment]
你是不是才升级过，我刚发现 repliaction 的数据新旧版本不兼容了。。。

**Comment by siddontang** [comment]
nohup 那个问题，你是不是直接在 console 控制台启动的，然后关闭了 session？如果是这样，很有可能也会关掉 nohup 启动的。你可以将 nohup 命令放到一个脚本文件里面执行。

**Comment by siddontang** [comment]
第二个我应该已经 fix 了，不过你的备份数据可能已经坏了，保险起见，可以将所有 master 和 slave 的 rpl 目录东西全部删除，然后在重新启动集群了。。。

**Comment by penuel-leo** [comment]
OK，已经好了；
顺便提一句，Makefile里面少了ledis-server和ledis-cli命令的编译。
```shell
go build -o bin/ledis-server -tags '$(GO_BUILD_TAGS)' cmd/ledis-server/*
go build -o bin/ledis-cli -tags '$(GO_BUILD_TAGS)' cmd/ledis-cli/*
```

**Comment by penuel-leo** [comment]
@siddontang 
当我直接get 数字的时候，会返回特殊的值:
>127.0.0.1:6380> get 1
"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
127.0.0.1:6380> get b
(nil)
127.0.0.1:6380> get 2
"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
127.0.0.1:6380> get 3
"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
127.0.0.1:6380> get 1000
"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
127.0.0.1:6380> set 1 2
OK
127.0.0.1:6380> get 1
"2"


2:xmigrate是原子的吗？如果把db0的数据migrate到db1，后续写的数据是不是还在db0上？

**Comment by siddontang** [comment]
del 1000 之后在 get 1000 看看呢？会不会是你直接同步数据的时候出了问题，因为之前有 bug。。。

**Comment by penuel-leo** [comment]
del之后，再get就对了，可是老数据里面没数字key，而且按照你说的，我把rpl下面的都删了，同步过程也没报错，
这些key不知道从哪出来的。

**Comment by siddontang** [comment]
之前错误的同步导致的问题
