### ISSUE TITLE
Replace CGO Lua with GopherLua

### ISSUE THREAD

**Issue by GlenDC** [siddontang/ledisdb#288]
The Lua support as it is, works, but relies on CGO, which makes the embedding of LedisDB no pure Go, the way it is supposed to be (possible).

Would it be possible to replace https://github.com/siddontang/golua with https://github.com/yuin/gopher-lua? I would be willing to put dev time into making this happen as a priority, as the dependency on CGO isn't desired.

Please let me know your opinion on this @siddontang and thank you very much for the time and effort you've put into ledisdb!

**Comment by siddontang** [comment]
Hi @GlenDC 

It is great if we can use pure GO LUA implementation. But I have no time this week, will see it next weekend. 

You can send me a PR too. Thanks.

**Comment by GlenDC** [comment]
Hi @siddontang a PR is open for this :) The unit tests pass, and I've also tested it manually with some stuff, and it all seems to hold up fine. Up to you to be the final judge of course.
