### ISSUE TITLE
add badger support

### ISSUE THREAD

**Issue by siddontang** [siddontang/ledisdb#296]
It is a good try to embed badger https://github.com/dgraph-io/badger, but now badger misses snapshot (https://github.com/dgraph-io/badger/issues/39), so we can't do replication or dump. 

And badger's iterator API is different from RocksDB's, so we must change our iterator interface at first, only support Next for either forward or reverse scan, luckily, we don't have any case that using an iterator bidirectionally.

**Comment by siddontang** [comment]
I will close it because badger won't support snapshot now.

**Comment by palamccc** [comment]
Any plan to support Badger ? Badger claims to have snapshot support. https://github.com/dgraph-io/badger/issues/39

**Comment by siddontang** [comment]
Hi @palamccc 

Have the plan, but now short of time, maybe later to rewrite whole code.
