### ISSUE TITLE
Consider to add Badger as the store engine in Ledis

### ISSUE THREAD

**Issue by FreedomMatrix2015** [siddontang/ledisdb#308]
The graph database "Dgraph"(https://github.com/dgraph-io/dgraph, 3.5k stars) use a Go language written KV store engine "Badger"(https://github.com/dgraph-io/badger, 2.2k stars).It seems that the Badger use LSM tree like RocksDB,which has better write performance than B tree like BoltDB.If Ledis use Badger as the sotre engine,it don`t need to call Cgo to link RocksDB.
So do u want to add Badger in Ledis?

**Comment by siddontang** [comment]
Hi @FreedomMatrix2015 

see https://github.com/siddontang/ledisdb/issues/296

**Comment by FreedomMatrix2015** [comment]
but why must do replication or dump?To make master-slave？
