### ISSUE TITLE
如何将leveldb或者rocksdb静态链接，想打包成二进制直接用

### ISSUE THREAD

**Issue by zhenruyan** [siddontang/ledisdb#309]
安装leveldb时看文档需要sudo 希望可以打包成完整的二进制 方便部署

**Comment by siddontang** [comment]
rocksdb 有一个 c-rocksdb，但我还没测试过，如果可以，后面可以直接用
但 leveldb 我没找到过

**Comment by zhenruyan** [comment]
goleveldb  就是静态链接的leveldb是吧？

**Comment by siddontang** [comment]
不是
