### ISSUE TITLE
BRPop: Never returns (sometimes) even if the queue has data

### ISSUE THREAD

**Issue by muhamadazmy** [siddontang/ledisdb#314]
Hello @siddontang
I get this weird issue that sometimes my app can not pop any more objects from a ledis list even if the queue is full. 

I embed ledis into the app, by starting a ledis app, and then internally access the database directly. I created a gist [here](https://gist.github.com/muhamadazmy/cfca4d37b111f6beb23925d2369b384c) that has a similar structure with my app, and at the same time produces the issue.

When u run this gist, the counter will keep counting up until some random point it will block and never increase again, if u try to connect with an external redis client (I use redis-cli) to port 7000 and check the length of the queue, u will see that it keeps growing up, and also u can do BRPop normally, it's only the code inside the app what blocks.

Thanks.

**Comment by siddontang** [comment]
Thanks @muhamadazmy 

I think I have found the concurrent problem. I will explain briefly.

For BRPop, the flow (we will use a for the flow here) is 

1. Try to pop the list, if pop one, return directly
2. If the list is empty, add a signal handler to with the pop key.
3. Wait for the signal.

For LPush, the flow (b) is

1. Push the list
2. If the key has an associated signal handler, signal it.

So the concurrent problem may happend at https://github.com/siddontang/ledisdb/blob/master/ledis/t_list.go#L791

The flow is a1 -> a2 -> b1 -> b2 -> a3 
As you can see, if we can't notify the chan, we will ignore it directly, this may cause b3 wait forever.

Maybe the simplest way to fix is to change https://github.com/siddontang/ledisdb/blob/master/ledis/t_list.go#L695 with `ch := make(chan []byte), len(keys))`, can you help me to check whether it works or not?

**Comment by muhamadazmy** [comment]
Hello @siddontang 
Thanks a lot for the fast response. I applied your change and it indeed fixed it. It tried to run my gist again once your fix was in place, it doesn't block forever anymore. 

Could you please commit this change to master ?
```diff
diff --git a/ledis/t_list.go b/ledis/t_list.go
index 718ad8e..5002166 100644
--- a/ledis/t_list.go
+++ b/ledis/t_list.go
@@ -692,7 +692,7 @@ func (db *DB) LKeyExists(key []byte) (int64, error) {
 }
 
 func (db *DB) lblockPop(keys [][]byte, whereSeq int32, timeout time.Duration) ([]interface{}, error) {
-	ch := make(chan []byte)
+	ch := make(chan []byte, len(keys))
 
 	bkeys := [][]byte{}
 	for _, key := range keys {
```
