### ISSUE TITLE
ledisdb rocksdb  放了很多数据．数据文件到20G后不再增长．　默认配制没改．

### ISSUE THREAD

**Issue by wxf4150** [siddontang/ledisdb#320]

**Comment by siddontang** [comment]
没明白不再增长的意思？是数据插入不进去？

**Comment by wxf4150** [comment]
我详细测试了下，应试正常写入，是我搞错了。 
测试中发现：
相比使用Lib的 方式 ， 用ledis-server 会占用不少内存（2-3G左右），这是正常的吗？
![2017-08-28 15-44-17](https://user-images.githubusercontent.com/5011771/29763931-cc042f92-8c07-11e7-989d-803907acee60.png)

写了20GB 数据，机械硬盘。
写的文件比较大。
ledis_server buffer要设10M ；要不然会出错。
   conn_read_buffer_size = 10240000
   conn_write_buffer_size = 10240000
用github.com/go-redis/redis 连接测试的，测试时增加redisClient 的超时为10秒。
可能机械硬盘慢的原因，测一段时间还是会出这样的错 (*net.TCPAddr)(0xc4203b4600), Err:(*net.timeoutError)(0xd35820)}

测试代码如下，：
`func Test_Ledis_Server(t *testing.T){
	//bs,err:=ioutil.ReadFile("/home/wxf/下载/rocksdb-5.7.2.tar.gz") //大文件3865045Byte(3.9M) 
	bs,err:=ioutil.ReadFile("/home/wxf/下载/a.jpg") //小文件234680 Byte(234K) 
	assert.Equal(t,nil,err,"文件没有正常读取")
	
	allbs:=0
	for i:=0;i<1024*15*1000;i++{
		gbs:=allbs/1024/1024/1024
		if gbs>22{ //最多试到22G
			t.Log("总共",strconv.Itoa(gbs),"GB count:",i+1)
			break;
		}
		err:= RClient.HSet("testfile3",strconv.Itoa(i),bs).Err()
		assert.Equal(t,nil,err,"ledis_server insert错误:","writeSize:",gbs," writeCount:",i)
		allbs+=234680

	}
	t.Log("insert finish")
}
`
