### ISSUE TITLE
When can we expect 0.6 release?

### ISSUE THREAD

**Issue by c2h5oh** [siddontang/ledisdb#324]
I could really use TLS support, but I'd rather pin to a version, not commit.

**Comment by siddontang** [comment]
@c2h5oh 

I think we can pin after #325

**Comment by c2h5oh** [comment]
I'll add a dockerfile tomorrow - let's include it too.

**Comment by c2h5oh** [comment]
Preparatory work for Dockerfile is in this pull request https://github.com/siddontang/ledisdb/pull/326

Final pull request will follow in the next hour or so.

**Comment by c2h5oh** [comment]
Final pull request - Dockefile to allow building new version - https://github.com/siddontang/ledisdb/pull/327

**Comment by c2h5oh** [comment]
With all 3 merged let's tag it 0.6
