### ISSUE TITLE
When the master using a password, slave replication fails

### ISSUE THREAD

**Issue by benjafire** [siddontang/ledisdb#333]
In server/replaction.go line 106 checkConn function, it doesn't send "auth" command to the master when necessary . So it will cause the "none auth" failure. Try to fix it and change the function like this:
![image](https://user-images.githubusercontent.com/9316473/37454199-e1423796-2874-11e8-894f-3530572478e4.png)
At the same time, config/config.go should add this new field into the RepliactionConfig structure.
![image](https://user-images.githubusercontent.com/9316473/37454235-fc1f9cac-2874-11e8-887a-385302fe0eee.png)

Hope this can be fixed soon, cause I don't wan to let the master running without the password protection in order to achieve the slave replication. :-)

**Comment by siddontang** [comment]
Thanks @benjafire 

Can we send me a PR?

**Comment by benjafire** [comment]
@siddontang , Sorry for replying so late. The PR has been created. https://github.com/siddontang/ledisdb/pull/336 . Hope this project gets better and better. :-)
