### ISSUE TITLE
Great software! 3 questions

### ISSUE THREAD

**Issue by unisqu** [siddontang/ledisdb#354]
1. Any lib example? Trying to use as a package ledis. cant seem to find any useful information on how to use as a package

I'm running golang as "daemon" and doesnt work this way, how do I resolve?

                     var cfg = lediscfg.NewConfigDefault()
                     cfg.DBName := "RAM"

returns
        
                      syntax error: non-declaration statement outside function body

I don't understand how to properly get the values of the list

               list, _   := fcachedb.HMget([]byte("key"),[]byte("value1"),[]byte("value2"))... etc up to "value8"

how do I get individual items on the list?

2. when will multi-exec be implemented?

3. why use boltdb when performance is much terrible than leveldb etc?

**Comment by siddontang** [comment]
1. can you provide the test code?  HMget is for hash, for for list. 
2. No plan now
3. One is Go vs C++, the other may B+ Tree vs LSM.

**Comment by unisqu** [comment]
1. What I would like to achieve:
https://pastebin.com/raw/DZheFgwX

2. OK.

3. Alright. Thanks. Appreciate this.

**Comment by unisqu** [comment]
Very good.
