### ISSUE TITLE
memory backend crashes when loading config

### ISSUE THREAD

**Issue by ghost** [siddontang/ledisdb#390]
Hello,

I was able to create a segfault in ledis. To reproduce this behavior, perform the following steps:

1. clone ledisdb
2. change config.toml db_name = "memory"
3. disable TLS in the config:
+#[tls]
+#enabled = true
+#certificate = "test.crt"
+#key = "test.key" 

4. run bin/ledis -c config/config.toml

observe:
Version 0.6+26-gd35789e
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7c3b4e]

goroutine 16 [running]:
sync.(*RWMutex).RLock(...)
	/home/rbastic/.go/src/sync/rwmutex.go:48
github.com/ledisdb/ledisdb/config.(*Config).GetReadonly(0xc000240580, 0x8614a0)
	/home/rbastic/go/src/github.com/ledisdb/ledisdb/config/config.go:308 +0x2e
github.com/ledisdb/ledisdb/ledis.(*Ledis).IsReadOnly(0xc00029e0c0, 0xc00438bf04)
	/home/rbastic/go/src/github.com/ledisdb/ledisdb/ledis/ledis.go:190 +0x2e
github.com/ledisdb/ledisdb/ledis.(*Ledis).checkTTL.func1(0xc00029e0c0)
	/home/rbastic/go/src/github.com/ledisdb/ledisdb/ledis/ledis.go:218 +0x2c4
created by github.com/ledisdb/ledisdb/ledis.(*Ledis).checkTTL
	/home/rbastic/go/src/github.com/ledisdb/ledisdb/ledis/ledis.go:209 +0xfa

While it is possibly not the best fix, the following patch appears to resolve this:

--- a/config/config.go
+++ b/config/config.go
@@ -172,6 +172,7 @@ func NewConfigWithData(data []byte) (*Config, error) {
                return nil, fmt.Errorf("newConfigwithData: unmarashal: %s", err)
        }
 
+       cfg.m = new(sync.RWMutex)
        cfg.adjust()
 
Kind regards,

edit: Grammar

**Comment by lunny** [comment]
@rbastic Thanks! Would you like to send a PR to fix that?

**Comment by dteh** [comment]
I only came across this issue when building the docker image, not when building from source. I found the issue was that the toml parser was ignoring the `toml: "-"` tag and overwriting the mutex with nil.
It was resolved by replacing the toml parser with https://github.com/pelletier/go-toml/v2 
I've forked and fixed it (with various other updates) here: https://github.com/sunday-software/ledisdb
