### ISSUE TITLE
Docker build fails on apple m1

### ISSUE THREAD

**Issue by aminroosta** [siddontang/ledisdb#406]
I get the following error:

<summary>

<details>
 <pre><code>
/Users/amin/projects/ledisdb $ docker build -t ledisdb:0.6 .
[+] Building 4.0s (13/21)
 => [internal] load build definition from Dockerfile                                                                                                     0.6s
 => => transferring dockerfile: 4.05kB                                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                                        0.7s
 => => transferring context: 2B                                                                                                                          0.0s
 => [internal] load metadata for docker.io/library/debian:stretch-slim                                                                                   1.3s
 => [internal] load metadata for docker.io/library/golang:1.9-stretch                                                                                    1.4s
 => [internal] load build context                                                                                                                        0.8s
 => => transferring context: 434B                                                                                                                        0.0s
 => [builder 1/8] FROM docker.io/library/golang:1.9-stretch@sha256:188abcc68745d3a429313f18c73d65ffa449a11443a374931988adcd3089afb1                      0.0s
 => CACHED [stage-1 1/8] FROM docker.io/library/debian:stretch-slim@sha256:77673099250866831667f36400e530893fc163fc36cec947cc11ff4c4464ec17              0.0s
 => CACHED [builder 2/8] WORKDIR /build                                                                                                                  0.0s
 => CACHED [builder 3/8] RUN apt-get update &&     apt-get install -y     ca-certificates     wget     gcc-6     g++-6     build-essential     libsnapp  0.0s
 => CACHED [builder 4/8] RUN wget -O ledisdb-src.tar.gz "https://github.com/ledisdb/ledisdb/archive/v0.6.tar.gz" &&     tar -zxf ledisdb-src.tar.gz &&   0.0s
 => CACHED [builder 5/8] RUN wget -O leveldb-src.tar.gz "https://github.com/google/leveldb/archive/47cb9e2a211e1d7157078ba7bab536beb29e56dc.tar.gz" &&   0.0s
 => CACHED [builder 6/8] RUN wget -O rocksdb-src.tar.gz "https://github.com/facebook/rocksdb/archive/v5.8.6.tar.gz" &&     tar -zxf rocksdb-src.tar.gz   0.0s
 => ERROR [builder 7/8] RUN export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/build/lib:/usr/lib &&     export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/build/lib:/  1.6s
------
 > [builder 7/8] RUN export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/build/lib:/usr/lib &&     export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/build/lib:/usr/lib &&     mkdir -p /build/bin &&     rm -rf /build/bin/* &&     cd /go/src/github.com/ledisdb/ledisdb &&     GOGC=off go build -i -o /build/bin/ledis-server -tags "snappy leveldb rocksdb" cmd/ledis-server/* &&     GOGC=off go build -i -o /build/bin/ledis-cli -tags "snappy leveldb rocksdb" cmd/ledis-cli/* &&     GOGC=off go build -i -o /build/bin/ledis-benchmark -tags "snappy leveldb rocksdb" cmd/ledis-benchmark/* &&     GOGC=off go build -i -o /build/bin/ledis-dump -tags "snappy leveldb rocksdb" cmd/ledis-dump/* &&     GOGC=off go build -i -o /build/bin/ledis-load -tags "snappy leveldb rocksdb" cmd/ledis-load/* &&     GOGC=off go build -i -o /build/bin/ledis-repair -tags "snappy leveldb rocksdb" cmd/ledis-repair/*:
#12 1.275 cmd/ledis-server/main.go:15:2: cannot find package "github.com/siddontang/ledisdb/config" in any of:
#12 1.275       /go/src/github.com/ledisdb/ledisdb/vendor/github.com/siddontang/ledisdb/config (vendor tree)
#12 1.275       /usr/local/go/src/github.com/siddontang/ledisdb/config (from $GOROOT)
#12 1.275       /go/src/github.com/siddontang/ledisdb/config (from $GOPATH)
#12 1.275 cmd/ledis-server/main.go:16:2: cannot find package "github.com/siddontang/ledisdb/server" in any of:
#12 1.275       /go/src/github.com/ledisdb/ledisdb/vendor/github.com/siddontang/ledisdb/server (vendor tree)
#12 1.275       /usr/local/go/src/github.com/siddontang/ledisdb/server (from $GOROOT)
#12 1.275       /go/src/github.com/siddontang/ledisdb/server (from $GOPATH)
------
executor failed running [/bin/sh -c export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/build/lib:/usr/lib &&     export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/build/lib:/usr/lib &&     mkdir -p /build/bin &&     rm -rf /build/bin/* &&     cd /go/src/github.com/ledisdb/ledisdb &&     GOGC=off go build -i -o /build/bin/ledis-server -tags "snappy leveldb rocksdb" cmd/ledis-server/* &&     GOGC=off go build -i -o /build/bin/ledis-cli -tags "snappy leveldb rocksdb" cmd/ledis-cli/* &&     GOGC=off go build -i -o /build/bin/ledis-benchmark -tags "snappy leveldb rocksdb" cmd/ledis-benchmark/* &&     GOGC=off go build -i -o /build/bin/ledis-dump -tags "snappy leveldb rocksdb" cmd/ledis-dump/* &&     GOGC=off go build -i -o /build/bin/ledis-load -tags "snappy leveldb rocksdb" cmd/ledis-load/* &&     GOGC=off go build -i -o /build/bin/ledis-repair -tags "snappy leveldb rocksdb" cmd/ledis-repair/*]: exit code: 1
  </code></pre>
</details>
</summary>

**Comment by dteh** [comment]
Fixed the docker image here (and included prebuilt images for arm64 and amd64)

https://github.com/sunday-software/ledisdb
